import 'package:analytics_sdk/manager/page_name_manager.dart';
import 'package:analytics_sdk/observer/page_lifecycle_observer.dart';

void initPage() {
  PageNameMapper.addMappings({
    'main': {'key': 'main', 'name': '主页面'},
    '': {'key': 'launch', 'name': '启动页'},
    'launch': {'key': 'launch', 'name': '启动页'},
    'home': {'key': 'home', 'name': '首页'},
    'anWang': {'key': 'anWang', 'name': '暗网页'},
    'vlog': {'key': 'vlog', 'name': '短视频页'},
    'ych': {'key': 'ych', 'name': '原创社区页'},
    'acg': {'key': 'acg', 'name': 'ACG页'},
    'community': {'key': 'community', 'name': '社区页'},
    'mine': {'key': 'mine', 'name': '我的'},
    'vlogSecond': {'key': 'vlogSecond', 'name': '短视频二级页'},
    'vlogTag/:tag': {'key': 'vlogTag', 'name': '短视频标签页'},
    'soulGroupChatList': {'key': 'soulGroupChatList', 'name': '群聊列表页'},
    'soulGroupChatTopMsg': {'key': 'soulGroupChatTopMsg', 'name': '群聊置顶消息页'},
    'soulGroupDetailChatList': {
      'key': 'soulGroupDetailChatList',
      'name': '群聊详情页'
    },
    'soulGroupMembersList': {'key': 'soulGroupMembersList', 'name': '群成员页'},
    'cartoon': {'key': 'cartoon', 'name': '动漫视频页'},
    'cartoonMore/:sort/:title': {'key': 'cartoonMore', 'name': '更多动漫页'},
    'cartoonDetail': {'key': 'cartoonDetail', 'name': '动漫详情页'},
    'game': {'key': 'game', 'name': '游戏页'},
    'gameMore/:sort/:title': {'key': 'gameMore', 'name': '更多游戏页'},
    'gameNav/:type/:title': {'key': 'gameNav', 'name': '游戏导航页'},
    'gameDetail': {'key': 'gameDetail', 'name': '游戏详情页'},
    'gameTag/:tag': {'key': 'gameTag', 'name': '游戏标签页'},
    'heiLiaoDetail': {'key': 'heiLiaoDetail', 'name': '黑料详情页'},
    'heiLiaoTagList': {'key': 'heiLiaoTagList', 'name': '黑料标签列表页'},
    'ziYuan': {'key': 'ziYuan', 'name': '资源页'},
    'ktloadwebview/:url': {'key': 'webview', 'name': '网页视图页'},
    'bitPostDetail/:id': {'key': 'bitPostDetail', 'name': '种子帖子详情页'},
    'mineVipCenter': {'key': 'mineVipCenter', 'name': 'VIP中心页'},
    'mineVipUpgrade': {'key': 'mineVipUpgrade', 'name': 'VIP升级页'},
    'mineCoinRecharge': {'key': 'mineCoinRecharge', 'name': '金币充值页'},
    'mineCoinDetail': {'key': 'mineCoinDetail', 'name': '金币明细页'},
    'rankList': {'key': 'rankList', 'name': '排行榜页'},
    'mineRechargeRecord/:type': {'key': 'mineRechargeRecord', 'name': '充值记录页'},
    'communityIssue/:type/:org': {'key': 'communityIssue', 'name': '发布帖子页'},
    'communityIssue/:type/:topicType': {'key': 'communityIssue', 'name': '发布帖子页'},
    'communityModule': {'key': 'communityModule', 'name': '社区模块页'},
    'communityTieztDetail/:id': {
      'key': 'communityTieztDetail',
      'name': '社区帖子详情页'
    },
    'checkFileTieztDetail/:id': {
      'key': 'checkFileTieztDetail',
      'name': '查档帖子详情页'
    },
    'login': {'key': 'login', 'name': '登录页'},
    'mineSetup': {'key': 'mineSetup', 'name': '设置页'},
    'mineShareToUser': {'key': 'mineShareToUser', 'name': '分享给用户页'},
    'mineShareToUserRecord': {'key': 'mineShareToUserRecord', 'name': '分享记录页'},
    'mineAgent': {'key': 'mineAgent', 'name': '代理页'},
    'mineAgentProfit': {'key': 'mineAgentProfit', 'name': '代理收益页'},
    'mineAgentPromoteData': {'key': 'mineAgentPromoteData', 'name': '代理推广数据页'},
    'customerService': {'key': 'customerService', 'name': '客服网页'},
    'mineWithdrawal/:isAgent': {'key': 'mineWithdrawal', 'name': '提现页'},
    'mineWithdrawalRecord': {'key': 'mineWithdrawalRecord', 'name': '提现记录页'},
    'mineWithdrawalBankList': {'key': 'mineWithdrawalBankList', 'name': '提现银行卡列表页'},
    'mineWelfare/:index': {'key': 'mineWelfare', 'name': '福利页'},
    'aiServer': {'key': 'aiServer', 'name': 'AI服务页'},
    'aiMagic': {'key': 'aiMagic', 'name': 'AI魔法页'},
    'aiArt': {'key': 'aiArt', 'name': 'AI美术页'},
    'aiNovel': {'key': 'aiNovel', 'name': 'AI小说页'},
    'aiAudio': {'key': 'aiAudio', 'name': 'AI语音页'},
    'aiNovelDetail': {'key': 'aiNovelDetail', 'name': 'AI小说详情页'},
    'aiFaceSwap': {'key': 'aiFaceSwap', 'name': 'AI换脸页'},
    'aiVideoFaceSwap': {'key': 'aiVideoFaceSwap', 'name': 'AI视频换脸页'},
    'aiOffDeRobe': {'key': 'aiOffDeRobe', 'name': 'AI脱衣页'},
    'aiKiss': {'key': 'aiKiss', 'name': 'AI接吻页'},
    'minePost': {'key': 'minePost', 'name': '我的帖子页'},
    'mineIncomeDetail': {'key': 'mineIncomeDetail', 'name': '收入明细页'},
    'mineCollection': {'key': 'mineCollection', 'name': '我的收藏页'},
    'userCenter/:aff': {'key': 'userCenter', 'name': '用户中心页'},
    'chatMessage/:toUuid/:nickName/:thumb': {
      'key': 'chatMessage',
      'name': '聊天消息页'
    },
    'mineFollowing': {'key': 'mineFollowing', 'name': '我的关注页'},
    'originalEnter': {'key': 'originalEnter', 'name': '原创入口页'},
    'communityTagDetail/:id': {'key': 'communityTagDetail', 'name': '社区标签详情页'},
    'mineBuy': {'key': 'mineBuy', 'name': '购买页'},
    'minAIRecord': {'key': 'minAIRecord', 'name': 'AI生成记录页'},
    'videoDetail': {'key': 'videoDetail', 'name': '视频详情页'},
    'voicePlayerContent': {'key': 'voicePlayerContent', 'name': '语音播放器内容页'},
    'livesDetail': {'key': 'livesDetail', 'name': '直播视频详情页'},
    'mineDownload': {'key': 'mineDownload', 'name': '我的下载页'},
    'mineFillCode/:title': {'key': 'mineFillCode', 'name': '填写邀请码页'},
    'mine_bind_email': {'key': 'mine_bind_email', 'name': '绑定邮箱页'},
    'mineHelp': {'key': 'mineHelp', 'name': '帮助页'},
    'mineOfficialGroup': {'key': 'mineOfficialGroup', 'name': '官方群页'},
    'search': {'key': 'search', 'name': '搜索页'},
    'searchResult/:title': {'key': 'searchResult', 'name': '搜索结果页'},
    'moreVideo/:name/:id': {'key': 'moreVideo', 'name': '更多视频页'},
    'mineMessageCenter': {'key': 'mineMessageCenter', 'name': '消息中心页'},
    'mineSystemMessage': {'key': 'mineSystemMessage', 'name': '系统消息页'},
    'mediaViewer': {'key': 'mediaViewer', 'name': '媒体查看页'},
    'localVideo': {'key': 'localVideo', 'name': '本地视频页'},
    'localVoice': {'key': 'localVoice', 'name': '本地语音播放页'},
    'aiMagicDetail': {'key': 'aiMagicDetail', 'name': 'AI魔法详情页'},
    'moreComic': {'key': 'moreComic', 'name': '更多漫画页'},
    'sortComic': {'key': 'sortComic', 'name': '漫画分类页'},
    'newComic': {'key': 'newComic', 'name': '最新漫画页'},
    'endComic': {'key': 'endComic', 'name': '完结漫画页'},
    'updatingComic': {'key': 'updatingComic', 'name': '连载漫画页'},
    'rankComic': {'key': 'rankComic', 'name': '漫画排行榜页'},
    'comicDetail': {'key': 'comicDetail', 'name': '漫画详情页'},
    'comicChapters': {'key': 'comicChapters', 'name': '漫画章节目录页'},
    'comicReader': {'key': 'comicReader', 'name': '漫画阅读页'},
    'novelDetail': {'key': 'novelDetail', 'name': '小说详情页'},
    'novelChapters': {'key': 'novelChapters', 'name': '小说章节目录页'},
    'novelReader': {'key': 'novelReader', 'name': '小说阅读页'},
    'moreNovel': {'key': 'moreNovel', 'name': '更多小说页'},
    'novelVoicePlayer': {'key': 'novelVoicePlayer', 'name': '小说音频播放页'},
    'novelSort': {'key': 'novelSort', 'name': '小说分类页'},
    'novelNew': {'key': 'novelNew', 'name': '小说最新页'},
    'noveUpdating': {'key': 'noveUpdating', 'name': '小说连载页'},
    'novelEnd': {'key': 'novelEnd', 'name': '小说完结页'},
    'chatDetail': {'key': 'chatDetail', 'name': '裸聊详情页'},
    'morePicture': {'key': 'morePicture', 'name': '更多色图页'},
    'pictureReader': {'key': 'pictureReader', 'name': '色图阅读页'},
    'picturePreView': {'key': 'picturePreView', 'name': '色图预览页'},
    'albumTag/:tag': {'key': 'albumTag', 'name': '色图标签页'},
    'yelllowPicture': {'key': 'yelllowPicture', 'name': '美图页'},
    'date': {'key': 'date', 'name': '约炮页'},
    'chat': {'key': 'chat', 'name': '裸聊页'},
    'chatIssue': {'key': 'chatIssue', 'name': '裸聊发布页'},
    'task': {'key': 'task', 'name': '签到页'},
    'live': {'key': 'live', 'name': '直播页'},
    'asmr': {'key': 'asmr', 'name': 'ASMR页'},
    'torrentDownload': {'key': 'torrentDownload', 'name': '种子下载页'},
  });

  final defaultPageKey = PageNameMapper.resolvePageInfo('launch').key;
  PageLifecycleObserver.recordNavigation(defaultPageKey);
}
